repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE.md
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      # lint & attempt to correct failures (e.g. pyupgrade)
      - id: ruff
        args: [--fix]
      # compatible replacement for black
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: poetry run mypy --config-file pyproject.toml ./
        pass_filenames: false
        language: system
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
